# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c460566de1305dbc4742f4fb0262ddae20fb82f3cb6c108e895459c2b4e99ba1821934d27e53f1b7655a8b631b0cfc7d02609e3db3bc52cc3027355af30685b

test:
  secret_key_base: 848ab62d53e5fb2b97e1e1e38696376887612dd05c2dba6a4480c0d78e823c586c2d60008eadd8ccebc3e5a2fb5c08bb2df343c08ecbf8bc9a84091a37d9da22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
